Repository opensearch-project/index-management, pull requests merged in 2022-07, with the labels that each got.

#405 2.1 release note
  release-notes/opensearch-index-management.release-notes-2.1.0.0.md
Labels: backport 2.1

#419 removed recursion from Explain Action to avoid stackoverflow in some …
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/explain/TransportExplainAction.kt
Labels: backport 1.x, backport 2.x

#418 Use disk stats, not RAM, for shrink action and node evaluation.
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptShrinkStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/StepUtils.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/StepUtilsTests.kt
Labels: backport 2.x

#409 Staging for version increment automation
  build.gradle
Labels: backport 2.1
