Repository opensearch-project/index-management, pull requests merged in 2022-04, with the labels that each got.

#323 Make sure qualifier default is alpha1 in IM
  .github/workflows/multi-node-test-workflow.yml
  .github/workflows/test-and-build-workflow.yml
  build.gradle
Labels: v2.0.0, release

#328 Fix metadata migration logic error when update setting call failed
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/MetadataService.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/MetadataServiceTests.kt
Labels: backport 1.x, backport 1.3

#334 Only download JS zip when integTest is running
  build.gradle
Labels: v2.0.0, release

#267 Updates search text field to keyword subfield for policies and managed indices
  build.gradle
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/explain/TransportExplainAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/getpolicy/TransportGetPoliciesAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/RestHandlerUtils.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/IndexStateManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/resthandler/IndexStateManagementRestApiIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/resthandler/RestExplainActionIT.kt
Labels: v2.0.0

#339 BugFix: Notification integration issues
  build.gradle
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexRunner.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/notification/AttemptNotificationStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/NotificationUtils.kt
Labels: v2.0.0

#337 Non-inclusive nonmenclature update
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexCoordinator.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexRunner.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/settings/LegacyOpenDistroManagedIndexSettings.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/settings/ManagedIndexSettings.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/explain/ExplainRequest.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/explain/TransportExplainAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/retryfailedmanagedindex/RetryFailedManagedIndexRequest.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/retryfailedmanagedindex/TransportRetryFailedManagedIndexAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/RollupMapperService.kt
  src/main/plugin-metadata/plugin-security.policy
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/coordinator/ManagedIndexCoordinatorTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/explain/ExplainRequestTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/retryfailedmanagedindex/RetryFailedManagedIndexRequestTests.kt
Labels: v2.0.0

#340 Fixes flaky continuous transforms and shrink tests
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptShrinkStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/StepUtils.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/ShrinkActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/model/ActionTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/RollupRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/runner/RollupRunnerIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRunnerIT.kt
Labels: backport 2.0

#342 Adds 2.0.0.0-rc1 release notes
  release-notes/opensearch-index-management.release-notes-2.0.0.0-rc1.md
Labels: backport 2.0

#345 Minor improvements
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexCoordinator.kt
  src/main/resources/mappings/opendistro-ism-config.json
  src/test/kotlin/org/opensearch/indexmanagement/IndexManagementRestTestCase.kt
  src/test/resources/mappings/cached-opendistro-ism-config.json
Labels: backport 2.0
