Repository opensearch-project/index-management, pull requests merged in 2022-10, with the labels that each got.

#434 Adds plugin version sweep background job
  src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/PluginVersionSweepCoordinator.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/SkipExecution.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/settings/ManagedIndexSettings.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/MetadataServiceTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/coordinator/SkipExecutionTests.kt
Labels: backport 2.x

#557 Update jackson to 2.13.4
  build.gradle
Labels: backport 1.x, backport 1.3, backport 2.0, backport 2.1, backport 2.x, backport 2.2, backport 2.3

#558 556: Moved _doc_count from transform._doc_count to root of document
  src/main/kotlin/org/opensearch/indexmanagement/transform/model/Transform.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRunnerIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/resthandler/RestPreviewTransformActionIT.kt
Labels: backport 2.x

#474 Feature/184 introduce security tests
  build.gradle
  src/main/kotlin/org/opensearch/indexmanagement/util/IndexManagementException.kt
  src/test/kotlin/org/opensearch/indexmanagement/AccessRoles.kt
  src/test/kotlin/org/opensearch/indexmanagement/IndexStateManagementSecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/RollupSecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/SecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/SecurityRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/TransformSecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/IndexStateManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/RollupRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRestTestCase.kt
Labels: backport 2.x

#576 Bugfix/538 transform lock expiration fix
  src/main/kotlin/org/opensearch/indexmanagement/transform/TransformRunner.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/TransformSearchService.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/action/explain/TransportExplainTransformAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/opensearchapi/OpenSearchExtensions.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/util/TransformContext.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/util/TransformLockManager.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/opensearchapi/ExtensionsTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/util/TransformContextTests.kt
Labels: backport 2.x, v2.4.0
