Repository opensearch-project/index-management, pull requests merged in 2022-08, with the labels that each got.

#439 moved _doc_count field from rollup._doc_count to root of document
  src/main/kotlin/org/opensearch/indexmanagement/rollup/model/Rollup.kt
Labels: backport 2.x

#435 added support for mustache scripting of rollup.target_index field
  src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/rollup/AttemptCreateRollupJobStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/RollupIndexer.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/RollupMapperService.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/action/index/TransportIndexRollupAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/action/mapping/TransportUpdateRollupMappingAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/util/RollupFieldValueExpressionResolver.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/RollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/util/RollupFieldValueExpressionResolverTests.kt
Labels: backport 2.x

#440 added support for searching multiple rollup indices with same mapping
  src/main/kotlin/org/opensearch/indexmanagement/rollup/interceptor/RollupInterceptor.kt
Labels: v2.2.0, backport 2.x

#450 Add 2.2 release note
  release-notes/opensearch-index-management.release-notes-2.2.0.0.md
Labels: backport 2.2

#461 [FIX] Failed concurrent creates of ISM policies should return http 409
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/indexpolicy/TransportIndexPolicyAction.kt
Labels: backport 2.x

#460 Change test page size to avoid index/search TimeInMillis < 1 issue.
  src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRunnerIT.kt
Labels: backport 1.x, backport 2.x

#477 Transform maxclauses fix
  src/main/kotlin/org/opensearch/indexmanagement/transform/TransformProcessedBucketLog.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/TransformRunner.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/TransformSearchService.kt
  src/main/kotlin/org/opensearch/indexmanagement/util/IndexUtils.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRunnerIT.kt
Labels: backport 1.x, backport 2.x
