Repository opensearch-project/index-management, pull requests merged in 2022-11, with the labels that each got.

#445 alias in rollup target_index field
  src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/RollupMapperService.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/settings/RollupSettings.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/util/RollupFieldValueExpressionResolver.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/util/RollupUtils.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/runner/RollupRunnerIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/util/RollupFieldValueExpressionResolverTests.kt
Labels: backport 2.x, v2.4.0

#575 Adds an alias action (#35)
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ISMActionsParser.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/AliasAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/AliasActionParser.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/alias/AttemptAliasActionsStep.kt
  src/main/resources/mappings/opendistro-ism-config.json
  src/test/kotlin/org/opensearch/indexmanagement/IndexManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/TestHelpers.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/AliasActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/model/XContentTests.kt
  src/test/resources/mappings/cached-opendistro-ism-config.json
  worksheets/ism/alias_action.http
Labels: backport 2.x, v2.4.0, backport 2.4

#595 Fix the compatibility issue of awareness replica validation
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/indexpolicy/TransportIndexPolicyAction.kt
Labels: backport 2.x, backport 2.4

#598 2.4 release note
  release-notes/opensearch-index-management.release-notes-2.4.0.0.md
Labels: backport 2.x, backport 2.4

#594 Fix a test in rollup target alias change
  src/main/kotlin/org/opensearch/indexmanagement/rollup/RollupMapperService.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/runner/RollupRunnerIT.kt
Labels: backport 2.x, backport 2.4

#609 Unify test clean logic
  .github/workflows/bwc-test-workflow.yml
  .github/workflows/multi-node-test-workflow.yml
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexRunner.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/explain/TransportExplainAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/util/JobSchedulerUtils.kt
  src/test/kotlin/org/opensearch/indexmanagement/IndexManagementIndicesIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/IndexManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/IndexStateManagementSecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/ODFERestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/RollupSecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/SecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/TransformSecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/bwc/IndexManagementBackwardsCompatibilityIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/IndexStateManagementIntegTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/IndexStateManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/ActionTimeoutIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/refreshanalyzer/RefreshSearchAnalyzerActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/refreshanalyzer/RestRefreshSearchAnalyzerActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/RollupRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/runner/RollupRunnerIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/snapshotmanagement/SnapshotManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRestTestCase.kt
Labels: maintenance, backport 2.x

#611 Security Workflow
  .github/workflows/docker-security-test-workflow.yml
  .github/workflows/security-test-workflow.yml
  .gitignore
  build.gradle
  src/main/kotlin/org/opensearch/indexmanagement/rollup/action/index/TransportIndexRollupAction.kt
  src/test/kotlin/org/opensearch/indexmanagement/ODFERestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/RolloverActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/refreshanalyzer/RefreshSearchAnalyzerActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/RollupRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestStartRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestStopRollupActionIT.kt
Labels: CI/CD, backport 2.x
