Repository opensearch-project/index-management, pull requests merged in 2023-04, with the labels that each got.

#718 Shrink action Fix
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/ShrinkAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptShrinkStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/ShrinkStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/WaitForMoveShardsStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/WaitForShrinkStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/StepUtils.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/StepUtilsTests.kt
Labels: backport main, needs-documentation

#729 Error Prevention: Add index priority action
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ActionValidation.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ValidateIndexPriority.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ValidateIndexPriorityIT.kt
Labels: backport 2.x

#732 Error Prevention: Add notification, shrink, allocation and rollup
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ActionValidation.kt
Labels: backport 2.x

#728 Error Prevention: Add close action
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ActionValidation.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ValidateClose.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ValidateCloseIT.kt
Labels: backport 2.x

#744 Error Prevention: Add transition action
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ActionValidation.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ValidateTransition.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ValidateTransitionIT.kt
Labels: backport 2.x

#745 Error Prevention: Add snapshot action
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ActionValidation.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ValidateSnapshot.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/validation/ValidateSnapshotIT.kt
Labels: backport 2.x

#755 Added 2.7 release notes.
  release-notes/opensearch-index-management.release-notes-2.7.0.0.md
Labels: backport 2.x, backport 2.7
