Repository opensearch-project/index-management, pull requests merged in 2023-09, with the labels that each got.

#911 Set preference to _primary when searching control-center index
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/action/get/TransportGetLRONConfigAction.kt
Labels: backport 2.x

#912 Add primary first preference to all search requests
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexCoordinator.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/explain/TransportExplainAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/getpolicy/TransportGetPoliciesAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/indexpolicy/TransportIndexPolicyAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/ManagedIndexUtils.kt
Labels: backport 2.x, v2.10.0

#916 Fix intelliJ IDEA gradle sync error
  build-tools/pkgbuild.gradle
Labels: backport 2.x

#919 make control center index as system index
  src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
Labels: backport 2.x

#921 Updates demo certs used in integ tests
  src/test/resources/security/esnode-key.pem
  src/test/resources/security/esnode.pem
  src/test/resources/security/kirk-key.pem
  src/test/resources/security/kirk.pem
  src/test/resources/security/root-ca.pem
  src/test/resources/security/sample.pem
  src/test/resources/security/test-kirk.jks
Labels: backport 2.x, v2.10.0

#925 Added 2.10 release notes
  release-notes/opensearch-index-management.release-notes-2.10.0.0.md
Labels: backport 2.x, backport 2.10
