Repository opensearch-project/index-management, pull requests merged in 2023-02, with the labels that each got.

#585 Bump main to 3.0.0
  .github/workflows/bwc-test-workflow.yml
  .github/workflows/docker-security-test-workflow.yml
  .github/workflows/multi-node-test-workflow.yml
  .github/workflows/release-workflow.yml
  .github/workflows/security-test-workflow.yml
  .github/workflows/test-and-build-workflow.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  spi/src/main/kotlin/org.opensearch.indexmanagement.spi/indexstatemanagement/model/ActionMetaData.kt
  spi/src/main/kotlin/org.opensearch.indexmanagement.spi/indexstatemanagement/model/PolicyRetryInfoMetaData.kt
  spi/src/main/kotlin/org.opensearch.indexmanagement.spi/indexstatemanagement/model/StateMetaData.kt
  spi/src/main/kotlin/org.opensearch.indexmanagement.spi/indexstatemanagement/model/StepMetaData.kt
  spi/src/main/kotlin/org.opensearch.indexmanagement.spi/indexstatemanagement/model/ValidationResult.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/util/QueryShardContextFactory.kt
  src/test/kotlin/org/opensearch/indexmanagement/IndexManagementIndicesIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/IndexManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/IndexStateManagementSecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/ODFERestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/RollupSecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/SecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/SecurityRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/TestHelpers.kt
  src/test/kotlin/org/opensearch/indexmanagement/TransformSecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/bwc/IndexManagementBackwardsCompatibilityIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/IndexStateManagementIntegTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/IndexStateManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/ActionRetryIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/IndexPolicyActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/RolloverActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/RollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/ShrinkActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/resthandler/IndexStateManagementRestApiIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/resthandler/RestAddPolicyActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/RollupRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/actionfilter/FieldCapsFilterIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/interceptor/RollupInterceptorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/runner/RollupRunnerIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/snapshotmanagement/SnapshotManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/snapshotmanagement/resthandler/RestGetSnapshotManagementIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRunnerIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/util/IndexUtilsTests.kt
Labels: maintenance

#690 Added Publish snapshots to maven via GHA workflow
  .github/workflows/maven-publish.yml
  build.gradle
Labels: backport 2.x, backport 2.6

#693 2.6 release note
  release-notes/opensearch-index-management.release-notes-2.6.0.0.md
Labels: backport 2.x
