Repository opensearch-project/index-management, pull requests merged in 2023-11, with the labels that each got.

#987 Support switch aliases in shrink action.
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/ShrinkAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/ShrinkActionParser.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/WaitForShrinkStep.kt
  src/main/resources/mappings/opendistro-ism-config.json
  src/test/kotlin/org/opensearch/indexmanagement/IndexManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/TestHelpers.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/ShrinkActionIT.kt
  src/test/resources/mappings/cached-opendistro-ism-config.json
Labels: backport 2.x, needs-documentation

#1035 Added unit test for switchAliases method.
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/WaitForShrinkStep.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/WaitForShrinkStepTests.kt
Labels: backport 2.x

#1036 Interval schedule should take start time from the request, should not…
  src/main/kotlin/org/opensearch/indexmanagement/transform/model/Transform.kt
Labels: backport 2.x, transform, v2.12.0

#1026 Added minimum for search.cancel_after_time_interval setting for rollups
  src/main/kotlin/org/opensearch/indexmanagement/rollup/RollupSearchService.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/settings/RollupSettings.kt
Labels: backport 2.x

#1042 Update 2.11.1 release note
  release-notes/opensearch-index-management.release-notes-2.11.0.0.md
  release-notes/opensearch-index-management.release-notes-2.11.1.0.md
Labels: backport 2.x, backport 2.11

#1040 Interval schedule should take start time from the request, should not…
  src/main/kotlin/org/opensearch/indexmanagement/rollup/model/Rollup.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/runner/RollupRunnerIT.kt
Labels: backport 2.x
