Repository opensearch-project/index-management, pull requests merged in 2023-05, with the labels that each got.

#773 Rollup Interceptor sourceIndex NPE fix
  src/main/kotlin/org/opensearch/indexmanagement/rollup/interceptor/RollupInterceptor.kt
  src/main/kotlin/org/opensearch/indexmanagement/util/IndexUtils.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/interceptor/RollupInterceptorIT.kt
Labels: backport 2.x

#772 Date nanos rollup fix
  src/main/kotlin/org/opensearch/indexmanagement/rollup/RollupMetadataService.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/util/RollupUtils.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/RollupMetadataServiceTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/runner/RollupRunnerIT.kt
Labels: backport 2.x

#779 AddPolicyAction - Recursion removal
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/addpolicy/TransportAddPolicyAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/opensearchapi/OpenSearchExtensions.kt
  src/test/kotlin/org/opensearch/indexmanagement/IndexStateManagementSecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/PolicySecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/RollupSecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/SecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/SecurityRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/TransformSecurityBehaviorIT.kt
Labels: backport 2.x

#722 CRUD api for long running operation notification config
  src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/ControlCenterIndices.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/LRONConfigResponse.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/action/delete/DeleteLRONConfigAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/action/delete/DeleteLRONConfigRequest.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/action/delete/TransportDeleteLRONConfigAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/action/get/GetLRONConfigAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/action/get/GetLRONConfigRequest.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/action/get/GetLRONConfigResponse.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/action/get/TransportGetLRONConfigAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/action/index/IndexLRONConfigAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/action/index/IndexLRONConfigRequest.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/action/index/TransportIndexLRONConfigAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/model/LRONCondition.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/model/LRONConfig.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/resthandler/RestDeleteLRONConfigAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/resthandler/RestGetLRONConfigAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/resthandler/RestIndexLRONConfigAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/util/LRONUtils.kt
  src/main/kotlin/org/opensearch/indexmanagement/util/RestHandlerUtils.kt
  src/main/resources/mappings/opensearch-control-center.json
  src/test/kotlin/org/opensearch/indexmanagement/AccessRoles.kt
  src/test/kotlin/org/opensearch/indexmanagement/SecurityRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/LRONConfigSecurityBehaviorIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/SerializationTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/TestHelpers.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/XContentTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/action/ActionTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/resthandler/LRONConfigRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/resthandler/RestDeleteLRONConfigActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/resthandler/RestGetLRONConfigActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/resthandler/RestIndexLRONConfigActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/util/LRONUtilsTests.kt
Labels: backport 2.x, v2.8.0

#712 Feature/index operation notification
  build.gradle
  src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
  src/main/kotlin/org/opensearch/indexmanagement/common/model/rest/SearchParams.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/IndexOperationActionFilter.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/NotificationActionListener.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/OperationResult.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/parser/ActionRespParseResult.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/parser/ForceMergeIndexRespParser.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/parser/OpenIndexRespParser.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/parser/ReindexRespParser.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/parser/ResizeIndexRespParser.kt
  src/main/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/parser/ResponseParser.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/IndexOperationActionFilterTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/NotificationActionListenerIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/NotificationActionListenerTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/parser/BaseRespParserTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/parser/ForceMergeIndexRespParserTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/parser/OpenRespParserTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/parser/ReindexRespParserTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/controlcenter/notification/filter/parser/ResizeIndexRespParserTests.kt
Labels: backport 2.x, v2.8.0

#796 Use original PR numbers in 2.8 release notes.
  release-notes/opensearch-index-management.release-notes-2.8.0.0.md
Labels: backport 2.x, backport 2.8

#789 Support for system index interface
  src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
  src/main/kotlin/org/opensearch/indexmanagement/opensearchapi/OpenSearchExtensions.kt
  src/test/kotlin/org/opensearch/indexmanagement/IndexManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/TestHelpers.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestStartRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestStopRollupActionIT.kt
Labels: backport main

#622 Bugfix/202 transform date add date conversion
  src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
  src/main/kotlin/org/opensearch/indexmanagement/common/model/dimension/DateHistogram.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/TargetIndexMappingService.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/TransformIndexer.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/TransformRunner.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/TransformSearchService.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/action/preview/TransportPreviewTransformAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/util/TransformContext.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/util/TransformUtils.kt
  src/main/resources/mappings/opendistro-ism-config.json
  src/test/kotlin/org/opensearch/indexmanagement/IndexManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TargetIndexMappingServiceTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRunnerIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/resthandler/RestPreviewTransformActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/util/TransformContextTests.kt
  src/test/resources/mappings/cached-opendistro-ism-config.json
Labels: backport 2.x
