Repository opensearch-project/index-management, pull requests merged in 2023-10, with the labels that each got.

#968 Provide unique id for each rollup job and add debug logs
  src/main/kotlin/org/opensearch/indexmanagement/rollup/RollupMetadataService.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/RollupRunner.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/RollupRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestDeleteRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestGetRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestIndexRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestStartRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestStopRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/runner/RollupRunnerIT.kt
Labels: backport 2.x

#969 Security test filtered
  .github/workflows/docker-security-test-workflow.yml
  .github/workflows/security-test-workflow.yml
Labels: backport 2.x

#963 Refactor out the old cluster state metadata logic
  src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexCoordinator.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexRunner.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/opensearchapi/OpenSearchExtensions.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/settings/LegacyOpenDistroManagedIndexSettings.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/settings/ManagedIndexSettings.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/addpolicy/TransportAddPolicyAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/changepolicy/TransportChangePolicyAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/explain/TransportExplainAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/removepolicy/TransportRemovePolicyAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/retryfailedmanagedindex/TransportRetryFailedManagedIndexAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/updateindexmetadata/TransportUpdateManagedIndexMetaDataAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/updateindexmetadata/UpdateManagedIndexMetaDataAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/updateindexmetadata/UpdateManagedIndexMetaDataRequest.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/ManagedIndexUtils.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/RestHandlerUtils.kt
  src/test/kotlin/org/opensearch/indexmanagement/IndexManagementSettingsTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/coordinator/ManagedIndexCoordinatorTests.kt
Labels: v3.0.0

#966 Parallel test run
  .github/workflows/multi-node-test-workflow.yml
  .github/workflows/test-and-build-workflow.yml
  build.gradle
Labels: backport 2.x

#980 Add timeout for multinode tests
  src/test/kotlin/org/opensearch/indexmanagement/TestHelpers.kt
Labels: backport 2.x

#981 Fixing the flaky in rollup API test
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestDeleteRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestExplainRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestGetRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestIndexRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestStartRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestStopRollupActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RollupRestAPITestCase.kt
Labels: backport 2.x

#983 Fix the flaky in allocation IT during multinode test
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/AllocationActionIT.kt
Labels: backport 2.x

#986 Set the rollover action to idempotent
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/rollover/AttemptRolloverStep.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/RolloverActionIT.kt
Labels: backport 2.x

#760 [Feature] Support Transform as an ISM action
  DEVELOPER_GUIDE.md
  spi/src/main/kotlin/org.opensearch.indexmanagement.spi/indexstatemanagement/model/ActionProperties.kt
  spi/src/main/kotlin/org.opensearch.indexmanagement.spi/indexstatemanagement/model/TransformActionProperties.kt
  src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ISMActionsParser.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexCoordinator.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/TransformAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/TransformActionParser.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/transform/AttemptCreateTransformJobStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/transform/WaitForTransformCompletionStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/opensearchapi/OpenSearchExtensions.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/model/ISMTransform.kt
  src/main/resources/mappings/opendistro-ism-config.json
  src/main/resources/mappings/opendistro-ism-history.json
  src/test/kotlin/org/opensearch/indexmanagement/IndexManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/SecurityRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/IndexStateManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/TestHelpers.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/TransformActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/coordinator/ManagedIndexCoordinatorTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/AttemptCreateTransformJobStepTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/WaitForTransformCompletionStepTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TestHelpers.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/model/ISMTransformTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/model/WriteableTests.kt
  src/test/resources/mappings/cached-opendistro-ism-config.json
  src/test/resources/mappings/cached-opendistro-ism-history.json
Labels: backport 2.x, ism action, needs-documentation

#999 [Test] increase the wait time after transform job triggered
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/TransformActionIT.kt
Labels: backport 2.x

#1004 Drafted 2.11 release notes.
  release-notes/opensearch-index-management.release-notes-2.11.0.0.md
Labels: backport 2.x, backport 2.11

#1002 Backport #760 to 2.x
  DEVELOPER_GUIDE.md
  spi/src/main/kotlin/org.opensearch.indexmanagement.spi/indexstatemanagement/model/ActionProperties.kt
  spi/src/main/kotlin/org.opensearch.indexmanagement.spi/indexstatemanagement/model/TransformActionProperties.kt
  src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ISMActionsParser.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexCoordinator.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/TransformAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/TransformActionParser.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/transform/AttemptCreateTransformJobStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/transform/WaitForTransformCompletionStep.kt
  src/main/kotlin/org/opensearch/indexmanagement/opensearchapi/OpenSearchExtensions.kt
  src/main/kotlin/org/opensearch/indexmanagement/transform/model/ISMTransform.kt
  src/main/resources/mappings/opendistro-ism-config.json
  src/main/resources/mappings/opendistro-ism-history.json
  src/test/kotlin/org/opensearch/indexmanagement/IndexManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/SecurityRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/IndexStateManagementRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/TestHelpers.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/TransformActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/coordinator/ManagedIndexCoordinatorTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/AttemptCreateTransformJobStepTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/WaitForTransformCompletionStepTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TestHelpers.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRestTestCase.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/model/ISMTransformTests.kt
  src/test/kotlin/org/opensearch/indexmanagement/transform/model/WriteableTests.kt
  src/test/resources/mappings/cached-opendistro-ism-config.json
  src/test/resources/mappings/cached-opendistro-ism-history.json
Labels: v2.12.0

#967 Refactor change policy API and the policy in managed index to be non-null
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/DefaultIndexMetadataService.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexCoordinator.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexRunner.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/model/ManagedIndexConfig.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/opensearchapi/OpenSearchExtensions.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/settings/LegacyOpenDistroManagedIndexSettings.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/settings/ManagedIndexSettings.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/changepolicy/TransportChangePolicyAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/explain/TransportExplainAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/retryfailedmanagedindex/TransportRetryFailedManagedIndexAction.kt
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/ManagedIndexUtils.kt
  src/main/kotlin/org/opensearch/indexmanagement/rollup/util/RollupFieldValueExpressionResolver.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/TestHelpers.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/resthandler/RestChangePolicyActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/ManagedIndexUtilsTests.kt
Labels: refactor

#1000 Add more error notification at fail points
  src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexRunner.kt
Labels: backport 2.x

#1007 fix the race condition in test reset action start time
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/resthandler/RestRetryFailedManagedIndexActionIT.kt
Labels: backport 2.x

#1017 Improve security plugin enabling check
  .github/workflows/docker-security-test-workflow.yml
Labels: backport 2.x

#1025 Onboard jenkins prod docker images to github actions
  .github/workflows/multi-node-test-workflow.yml
  .github/workflows/release-workflow.yml
  .github/workflows/security-test-workflow.yml
  .github/workflows/test-and-build-workflow.yml
Labels: enhancement, backport 2.x

#1028 [Backport 2.x] Onboard jenkins prod docker images to github actions
  .github/workflows/multi-node-test-workflow.yml
  .github/workflows/release-workflow.yml
  .github/workflows/security-test-workflow.yml
  .github/workflows/test-and-build-workflow.yml
Labels: enhancement
