Repository opensearch-project/index-management, pull requests merged in 2024-07, with the labels that each got.

#1208 Fix github action
  .github/workflows/bwc-test-workflow.yml
  .github/workflows/docker-security-test-workflow.yml
  .github/workflows/multi-node-test-workflow.yml
  .github/workflows/security-test-workflow.yml
  .github/workflows/test-and-build-workflow.yml
Labels: backport 2.x

#1207 Add publish in spi build.gradle
  .github/workflows/maven-publish.yml
  build.gradle
  spi/build.gradle
Labels: release, backport 2.x

#1214 2.16 Release Notes
  release-notes/opensearch-index-management.release-notes-2.16.0.0.md
Labels: backport 2.x, backport 2.16
