Repository opensearch-project/index-management, pull requests merged in 2024-09, with the labels that each got.

#1238 Added release notes for v2.17
  release-notes/opensearch-index-management.release-notes-2.17.0.0.md
Labels: backport 2.x, backport 2.17

#1252 upgrade upload-artifact to version 3
  .github/workflows/bwc-test-workflow.yml
  .github/workflows/docker-security-test-workflow.yml
  .github/workflows/multi-node-test-workflow.yml
  .github/workflows/security-test-workflow.yml
  .github/workflows/test-and-build-workflow.yml
Labels: maintenance, backport 2.x, v2.18.0

#1251 Remove 2 instances wildcard imports
  src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/resthandler/RestChangePolicyActionIT.kt
  src/test/kotlin/org/opensearch/indexmanagement/rollup/resthandler/RestStartRollupActionIT.kt
Labels: backport 2.x

#1263 Move non-active maintainer to emeritus
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x
