Repository opensearch-project/index-management, pull requests merged in 2024-02, with the labels that each got.

#1088 Updates integTest behavior to run against local and remote cluster
  build.gradle
Labels: backport 2.x, v2.12.0

#1091 Fixes password assignment for integTest when using remote cluster
  build.gradle
Labels: backport 2.x, v2.12.0, backport 2.12

#1100 Accepts https as a property to set securityEnabled flag
  build.gradle
Labels: backport 2.x, v2.12.0, backport 2.12

#1092 Add v2.12.0 Release Notes
  release-notes/opensearch-index-management.release-notes-2.12.0.0.md
Labels: backport 2.x, backport 2.12

#1109 Update v2.12.0 Release Notes
  release-notes/opensearch-index-management.release-notes-2.12.0.0.md
Labels: backport 2.x, backport 2.12
